spring:
  redis:
    # Redis服务器地址
    host: ${redis.ip:127.0.0.1}
    # Redis服务器连接端口
    port: ${redis.port:6379}
    # Redis服务器连接密码
    password: ${redis.password:}
  #MySQL配置
  datasource:
    url: jdbc:mysql://${mysql.address:127.0.0.1:3306}/ols?serverTimezone=UTC&allowMultiQueries=true&useAffectedRows=true
    username: ${mysql.username:}
    password: ${mysql.password:}