spring:
  # 选择配置文件（dev：开发环境配置，pro：生产环境配置）
  profiles:
    　　active: dev
  redis:
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 5
  #MySQL配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  #数据库连接池
  type: com.alibaba.druid.pool.DruidDataSource

#mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#邮箱配置
email:
  #邮箱账户
  account: ${email.account:}
  #第三方代理授权码
  authorizationCode: ${email.authorizationCode:}
task:
  pool:
    #核心线程池大小
    corePoolSize: 10
    #最大线程数
    maxPoolSize: 20
    #活跃时间
    task.pool.keepAliveSeconds: 300
    #队列容量
    task.pool.queueCapacity: 20
