spring:
  redis:
    # Redis服务器地址
    host: ${redis.ip:127.0.0.1}
    # Redis服务器连接端口
    port: ${redis.port:6379}
    # Redis服务器连接密码
    password: ${redis.password:}
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 5
  #MySQL配置
  datasource:
    url: jdbc:mysql://${mysql.address:127.0.0.1:3306}/ols?serverTimezone=UTC&allowMultiQueries=true&useAffectedRows=true
    username: ${mysql.username:}
    password: ${mysql.password:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  #数据库连接池
  type: com.alibaba.druid.pool.DruidDataSource
#mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
