spring:
  redis:
    # Redis服务器地址
    host: ${redis.ip:127.0.0.1}
    # Redis服务器连接端口
    port: ${redis.port:6379}
    # Redis服务器连接密码
    password: ${redis.password:}
  #MySQL配置
  datasource:
    url: jdbc:mysql://${mysql.address:127.0.0.1:3306}/ols?serverTimezone=UTC&allowMultiQueries=true&useAffectedRows=true
    username: ${mysql.username:}
    password: ${mysql.password:}
#日志配置
log:
  path: /usr/local/logs
  level: DEBUG
  name: Ols_Project
#邮箱配置
email:
  #邮箱账户
  account: ${email.account:}
  #第三方代理授权码
  authorizationCode: ${email.authorizationCode:}